// Bundled demo data, generated by backend/scripts/export_demo.py with real engine scores.
import type { ProductResult } from '../api/types';
import data from './demoData.json';

const demo = data as unknown as {
  products: Record<string, ProductResult>;
  alternatives: Record<string, string[]>;
};

export function demoProduct(barcode: string): ProductResult | undefined {
  return demo.products[barcode];
}

export function demoAlternatives(barcode: string): ProductResult[] {
  return (demo.alternatives[barcode] ?? []).map((code) => demo.products[code]).filter(Boolean);
}

export function demoSearch(query: string): ProductResult[] {
  const q = query.trim().toLowerCase();
  return Object.values(demo.products).filter(
    (r) => r.product.name.toLowerCase().includes(q) || (r.product.brand ?? '').toLowerCase().includes(q),
  );
}

export function demoCatalogue(): ProductResult[] {
  return Object.values(demo.products);
}
